/// Record models for the goat (caprine) module.
///
/// All dates are ISO 8601 strings (YYYY-MM-DD). Numeric IDs are stable
/// string identifiers generated by the data layer.

// ── Weight ────────────────────────────────────────────────────────────────────

class WeightRecord {
  const WeightRecord({
    required this.id,
    required this.animalId,
    required this.date,
    required this.weightKg,
    this.bodyConditionScore,
    this.notes,
  });

  final String id;
  final String animalId;
  final String date;
  final double weightKg;
  final double? bodyConditionScore;
  final String? notes;

  factory WeightRecord.fromJson(Map<String, dynamic> j) => WeightRecord(
        id: j['id'] as String,
        animalId: j['animalId'] as String,
        date: j['date'] as String,
        weightKg: (j['weightKg'] as num).toDouble(),
        bodyConditionScore: (j['bodyConditionScore'] as num?)?.toDouble(),
        notes: j['notes'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'animalId': animalId,
        'date': date,
        'weightKg': weightKg,
        if (bodyConditionScore != null)
          'bodyConditionScore': bodyConditionScore,
        if (notes != null) 'notes': notes,
      };
}

// ── Breeding / Mating ─────────────────────────────────────────────────────────

class MatingRecord {
  const MatingRecord({
    required this.id,
    required this.doeId,
    required this.buckId,
    required this.serviceDate,
    required this.serviceMethod,
    this.expectedKiddingDate,
    required this.outcome,
    this.notes,
  });

  final String id;
  final String doeId;
  final String buckId;
  final String serviceMethod;
  final String serviceDate;
  final String? expectedKiddingDate;
  final String outcome;
  final String? notes;

  factory MatingRecord.fromJson(Map<String, dynamic> j) => MatingRecord(
        id: j['id'] as String,
        doeId: j['doeId'] as String,
        buckId: j['buckId'] as String,
        serviceDate: j['serviceDate'] as String,
        serviceMethod: j['serviceMethod'] as String,
        expectedKiddingDate: j['expectedKiddingDate'] as String?,
        outcome: j['outcome'] as String,
        notes: j['notes'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'doeId': doeId,
        'buckId': buckId,
        'serviceDate': serviceDate,
        'serviceMethod': serviceMethod,
        if (expectedKiddingDate != null)
          'expectedKiddingDate': expectedKiddingDate,
        'outcome': outcome,
        if (notes != null) 'notes': notes,
      };
}

// ── Pregnancy check ───────────────────────────────────────────────────────────

class PregnancyCheck {
  const PregnancyCheck({
    required this.id,
    required this.animalId,
    required this.date,
    required this.method,
    required this.result,
    this.expectedKiddingDate,
    this.daysPregnant,
    this.notes,
  });

  final String id;
  final String animalId;
  final String date;
  final String method;
  final String result;
  final String? expectedKiddingDate;
  final int? daysPregnant;
  final String? notes;

  factory PregnancyCheck.fromJson(Map<String, dynamic> j) => PregnancyCheck(
        id: j['id'] as String,
        animalId: j['animalId'] as String,
        date: j['date'] as String,
        method: j['method'] as String,
        result: j['result'] as String,
        expectedKiddingDate: j['expectedKiddingDate'] as String?,
        daysPregnant: j['daysPregnant'] as int?,
        notes: j['notes'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'animalId': animalId,
        'date': date,
        'method': method,
        'result': result,
        if (expectedKiddingDate != null)
          'expectedKiddingDate': expectedKiddingDate,
        if (daysPregnant != null) 'daysPregnant': daysPregnant,
        if (notes != null) 'notes': notes,
      };
}

// ── Kidding ───────────────────────────────────────────────────────────────────

class KiddingEvent {
  const KiddingEvent({
    required this.id,
    required this.damId,
    required this.kiddingDate,
    required this.totalKidsBorn,
    required this.kidsAliveBorn,
    required this.kidsStillborn,
    required this.birthWeights,
    required this.kidIds,
    required this.assisted,
    this.complications,
    this.notes,
  });

  final String id;
  final String damId;
  final String kiddingDate;
  final int totalKidsBorn;
  final int kidsAliveBorn;
  final int kidsStillborn;
  final List<double?> birthWeights;
  final List<String> kidIds;
  final bool assisted;
  final String? complications;
  final String? notes;

  factory KiddingEvent.fromJson(Map<String, dynamic> j) => KiddingEvent(
        id: j['id'] as String,
        damId: j['damId'] as String,
        kiddingDate: j['kiddingDate'] as String,
        totalKidsBorn: j['totalKidsBorn'] as int,
        kidsAliveBorn: j['kidsAliveBorn'] as int,
        kidsStillborn: j['kidsStillborn'] as int,
        birthWeights: (j['birthWeights'] as List<dynamic>)
            .map((e) => (e as num?)?.toDouble())
            .toList(),
        kidIds: (j['kidIds'] as List<dynamic>).cast<String>(),
        assisted: j['assisted'] as bool? ?? false,
        complications: j['complications'] as String?,
        notes: j['notes'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'damId': damId,
        'kiddingDate': kiddingDate,
        'totalKidsBorn': totalKidsBorn,
        'kidsAliveBorn': kidsAliveBorn,
        'kidsStillborn': kidsStillborn,
        'birthWeights': birthWeights,
        'kidIds': kidIds,
        'assisted': assisted,
        if (complications != null) 'complications': complications,
        if (notes != null) 'notes': notes,
      };
}

// ── Daily milk ────────────────────────────────────────────────────────────────

class DailyMilkRecord {
  const DailyMilkRecord({
    required this.id,
    required this.animalId,
    required this.date,
    required this.morningLitres,
    required this.eveningLitres,
    required this.lactationDay,
    this.notes,
  });

  final String id;
  final String animalId;
  final String date;
  final double morningLitres;
  final double eveningLitres;
  final int lactationDay;
  final String? notes;

  double get totalLitres => morningLitres + eveningLitres;

  factory DailyMilkRecord.fromJson(Map<String, dynamic> j) => DailyMilkRecord(
        id: j['id'] as String,
        animalId: j['animalId'] as String,
        date: j['date'] as String,
        morningLitres: (j['morningLitres'] as num).toDouble(),
        eveningLitres: (j['eveningLitres'] as num).toDouble(),
        lactationDay: j['lactationDay'] as int,
        notes: j['notes'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'animalId': animalId,
        'date': date,
        'morningLitres': morningLitres,
        'eveningLitres': eveningLitres,
        'lactationDay': lactationDay,
        if (notes != null) 'notes': notes,
      };
}

// ── Shearing ──────────────────────────────────────────────────────────────────

class ShearingRecord {
  const ShearingRecord({
    required this.id,
    required this.animalId,
    required this.shearingDate,
    required this.fleeceWeightKg,
    this.stapleLength,
    this.micron,
    this.colorGrade,
    this.pricePerKg,
    this.notes,
  });

  final String id;
  final String animalId;
  final String shearingDate;
  final double fleeceWeightKg;
  /// Staple length in mm.
  final double? stapleLength;
  /// Micron rating in µm.
  final double? micron;
  final String? colorGrade;
  final double? pricePerKg;
  final String? notes;

  double? get totalRevenue =>
      pricePerKg != null ? fleeceWeightKg * pricePerKg! : null;

  factory ShearingRecord.fromJson(Map<String, dynamic> j) => ShearingRecord(
        id: j['id'] as String,
        animalId: j['animalId'] as String,
        shearingDate: j['shearingDate'] as String,
        fleeceWeightKg: (j['fleeceWeightKg'] as num).toDouble(),
        stapleLength: (j['stapleLength'] as num?)?.toDouble(),
        micron: (j['micron'] as num?)?.toDouble(),
        colorGrade: j['colorGrade'] as String?,
        pricePerKg: (j['pricePerKg'] as num?)?.toDouble(),
        notes: j['notes'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'animalId': animalId,
        'shearingDate': shearingDate,
        'fleeceWeightKg': fleeceWeightKg,
        if (stapleLength != null) 'stapleLength': stapleLength,
        if (micron != null) 'micron': micron,
        if (colorGrade != null) 'colorGrade': colorGrade,
        if (pricePerKg != null) 'pricePerKg': pricePerKg,
        if (notes != null) 'notes': notes,
      };
}

// ── Health event ──────────────────────────────────────────────────────────────

class GoatHealthEvent {
  const GoatHealthEvent({
    required this.id,
    required this.animalId,
    required this.date,
    required this.condition,
    required this.severity,
    this.treatment,
    this.vet,
    this.outcome,
    this.notes,
  });

  final String id;
  final String animalId;
  final String date;
  final String condition;
  final String severity;
  final String? treatment;
  final String? vet;
  final String? outcome;
  final String? notes;

  factory GoatHealthEvent.fromJson(Map<String, dynamic> j) => GoatHealthEvent(
        id: j['id'] as String,
        animalId: j['animalId'] as String,
        date: j['date'] as String,
        condition: j['condition'] as String,
        severity: j['severity'] as String,
        treatment: j['treatment'] as String?,
        vet: j['vet'] as String?,
        outcome: j['outcome'] as String?,
        notes: j['notes'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'animalId': animalId,
        'date': date,
        'condition': condition,
        'severity': severity,
        if (treatment != null) 'treatment': treatment,
        if (vet != null) 'vet': vet,
        if (outcome != null) 'outcome': outcome,
        if (notes != null) 'notes': notes,
      };
}

// ── Medication log ────────────────────────────────────────────────────────────

class GoatMedicationLog {
  const GoatMedicationLog({
    required this.id,
    required this.animalId,
    required this.date,
    required this.drug,
    required this.dose,
    required this.route,
    this.reason,
    this.withdrawalDays,
    this.administeredBy,
    this.notes,
  });

  final String id;
  final String animalId;
  final String date;
  final String drug;
  final String dose;
  /// One of: oral / injection / topical / pour-on
  final String route;
  final String? reason;
  final int? withdrawalDays;
  final String? administeredBy;
  final String? notes;

  /// ISO date of the last withdrawal day, or null if none.
  String? get withdrawalExpiryDate {
    if (withdrawalDays == null || withdrawalDays == 0) return null;
    try {
      final start = DateTime.parse(date);
      return start
          .add(Duration(days: withdrawalDays!))
          .toIso8601String()
          .substring(0, 10);
    } catch (_) {
      return null;
    }
  }

  factory GoatMedicationLog.fromJson(Map<String, dynamic> j) =>
      GoatMedicationLog(
        id: j['id'] as String,
        animalId: j['animalId'] as String,
        date: j['date'] as String,
        drug: j['drug'] as String,
        dose: j['dose'] as String,
        route: j['route'] as String,
        reason: j['reason'] as String?,
        withdrawalDays: j['withdrawalDays'] as int?,
        administeredBy: j['administeredBy'] as String?,
        notes: j['notes'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'animalId': animalId,
        'date': date,
        'drug': drug,
        'dose': dose,
        'route': route,
        if (reason != null) 'reason': reason,
        if (withdrawalDays != null) 'withdrawalDays': withdrawalDays,
        if (administeredBy != null) 'administeredBy': administeredBy,
        if (notes != null) 'notes': notes,
      };
}

// ── Vaccination ───────────────────────────────────────────────────────────────

class GoatVaccination {
  const GoatVaccination({
    required this.id,
    required this.animalId,
    required this.vaccineName,
    required this.dueDate,
    this.givenDate,
    this.batchNumber,
    this.nextDueDate,
    this.administeredBy,
  });

  final String id;
  final String animalId;
  final String vaccineName;
  final String dueDate;
  final String? givenDate;
  final String? batchNumber;
  final String? nextDueDate;
  final String? administeredBy;

  bool get isOverdue {
    if (givenDate != null) return false;
    try {
      return DateTime.parse(dueDate).isBefore(DateTime.now());
    } catch (_) {
      return false;
    }
  }

  bool get isGiven => givenDate != null;

  factory GoatVaccination.fromJson(Map<String, dynamic> j) => GoatVaccination(
        id: j['id'] as String,
        animalId: j['animalId'] as String,
        vaccineName: j['vaccineName'] as String,
        dueDate: j['dueDate'] as String,
        givenDate: j['givenDate'] as String?,
        batchNumber: j['batchNumber'] as String?,
        nextDueDate: j['nextDueDate'] as String?,
        administeredBy: j['administeredBy'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'animalId': animalId,
        'vaccineName': vaccineName,
        'dueDate': dueDate,
        if (givenDate != null) 'givenDate': givenDate,
        if (batchNumber != null) 'batchNumber': batchNumber,
        if (nextDueDate != null) 'nextDueDate': nextDueDate,
        if (administeredBy != null) 'administeredBy': administeredBy,
      };
}

// ── Body condition score ──────────────────────────────────────────────────────

class BodyConditionRecord {
  const BodyConditionRecord({
    required this.id,
    required this.animalId,
    required this.date,
    required this.score,
    this.notes,
  });

  final String id;
  final String animalId;
  final String date;
  final double score;
  final String? notes;

  factory BodyConditionRecord.fromJson(Map<String, dynamic> j) =>
      BodyConditionRecord(
        id: j['id'] as String,
        animalId: j['animalId'] as String,
        date: j['date'] as String,
        score: (j['score'] as num).toDouble(),
        notes: j['notes'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'animalId': animalId,
        'date': date,
        'score': score,
        if (notes != null) 'notes': notes,
      };
}

// ── Sale record ───────────────────────────────────────────────────────────────

class GoatSaleRecord {
  const GoatSaleRecord({
    required this.id,
    required this.animalId,
    required this.saleDate,
    required this.buyerName,
    this.saleWeightKg,
    this.pricePerKg,
    this.totalRevenue,
    this.invoiceRef,
    this.notes,
  });

  final String id;
  final String animalId;
  final String saleDate;
  final String buyerName;
  final double? saleWeightKg;
  final double? pricePerKg;
  final double? totalRevenue;
  final String? invoiceRef;
  final String? notes;

  factory GoatSaleRecord.fromJson(Map<String, dynamic> j) => GoatSaleRecord(
        id: j['id'] as String,
        animalId: j['animalId'] as String,
        saleDate: j['saleDate'] as String,
        buyerName: j['buyerName'] as String,
        saleWeightKg: (j['saleWeightKg'] as num?)?.toDouble(),
        pricePerKg: (j['pricePerKg'] as num?)?.toDouble(),
        totalRevenue: (j['totalRevenue'] as num?)?.toDouble(),
        invoiceRef: j['invoiceRef'] as String?,
        notes: j['notes'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'animalId': animalId,
        'saleDate': saleDate,
        'buyerName': buyerName,
        if (saleWeightKg != null) 'saleWeightKg': saleWeightKg,
        if (pricePerKg != null) 'pricePerKg': pricePerKg,
        if (totalRevenue != null) 'totalRevenue': totalRevenue,
        if (invoiceRef != null) 'invoiceRef': invoiceRef,
        if (notes != null) 'notes': notes,
      };
}

// ── Feed record ───────────────────────────────────────────────────────────────

class GoatFeedRecord {
  const GoatFeedRecord({
    required this.id,
    required this.herdId,
    required this.date,
    required this.feedType,
    required this.quantityKg,
    this.costPerKg,
    this.notes,
  });

  final String id;
  final String herdId;
  final String date;
  final String feedType;
  final double quantityKg;
  final double? costPerKg;
  final String? notes;

  double? get totalCost =>
      costPerKg != null ? quantityKg * costPerKg! : null;

  factory GoatFeedRecord.fromJson(Map<String, dynamic> j) => GoatFeedRecord(
        id: j['id'] as String,
        herdId: j['herdId'] as String,
        date: j['date'] as String,
        feedType: j['feedType'] as String,
        quantityKg: (j['quantityKg'] as num).toDouble(),
        costPerKg: (j['costPerKg'] as num?)?.toDouble(),
        notes: j['notes'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'herdId': herdId,
        'date': date,
        'feedType': feedType,
        'quantityKg': quantityKg,
        if (costPerKg != null) 'costPerKg': costPerKg,
        if (notes != null) 'notes': notes,
      };
}

// ── Pasture / camp rotation ───────────────────────────────────────────────────

class PastureRecord {
  const PastureRecord({
    required this.id,
    required this.herdId,
    required this.campId,
    required this.entryDate,
    this.exitDate,
    this.estimatedHa,
    this.veldCondition,
    this.notes,
  });

  final String id;
  final String herdId;
  final String campId;
  final String entryDate;
  final String? exitDate;
  final double? estimatedHa;
  final String? veldCondition;
  final String? notes;

  factory PastureRecord.fromJson(Map<String, dynamic> j) => PastureRecord(
        id: j['id'] as String,
        herdId: j['herdId'] as String,
        campId: j['campId'] as String,
        entryDate: j['entryDate'] as String,
        exitDate: j['exitDate'] as String?,
        estimatedHa: (j['estimatedHa'] as num?)?.toDouble(),
        veldCondition: j['veldCondition'] as String?,
        notes: j['notes'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'herdId': herdId,
        'campId': campId,
        'entryDate': entryDate,
        if (exitDate != null) 'exitDate': exitDate,
        if (estimatedHa != null) 'estimatedHa': estimatedHa,
        if (veldCondition != null) 'veldCondition': veldCondition,
        if (notes != null) 'notes': notes,
      };
}

// ── FAMACHA score ─────────────────────────────────────────────────────────────

class FamachaRecord {
  const FamachaRecord({
    required this.id,
    required this.animalId,
    required this.date,
    required this.score,
    this.actionTaken,
    this.notes,
  });

  final String id;
  final String animalId;
  final String date;
  final int score;
  final String? actionTaken;
  final String? notes;

  factory FamachaRecord.fromJson(Map<String, dynamic> j) => FamachaRecord(
        id: j['id'] as String,
        animalId: j['animalId'] as String,
        date: j['date'] as String,
        score: j['score'] as int,
        actionTaken: j['actionTaken'] as String?,
        notes: j['notes'] as String?,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'animalId': animalId,
        'date': date,
        'score': score,
        if (actionTaken != null) 'actionTaken': actionTaken,
        if (notes != null) 'notes': notes,
      };
}
